// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saritasa.NetForge.Demo;

#nullable disable

namespace Saritasa.NetForge.Demo.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250605051341_AddDirector")]
    partial class AddDirector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("products_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tags_id");

                    b.HasKey("ProductsId", "TagsId")
                        .HasName("pk_product_product_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_product_product_tag_tags_id");

                    b.ToTable("product_product_tag", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name")
                        .HasComputedColumnSql("city || ', ' || street", true);

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("street");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", null, t =>
                        {
                            t.HasComment("Represents the address of the shop.");
                        });
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<TimeSpan?>("AvailabilityDuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("availability_duration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_contact_infos");

                    b.ToTable("contact_infos", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AveragePurchaseCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("average_purchase_count");

                    b.Property<long>("Barcode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("barcode");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("EndOfSalesDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_of_sales_date");

                    b.Property<float>("HeightInCentimeters")
                        .HasColumnType("REAL")
                        .HasColumnName("height_in_centimeters");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_available");

                    b.Property<bool?>("IsSalesEnded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sales_ended");

                    b.Property<float>("LengthInCentimeters")
                        .HasColumnType("REAL")
                        .HasColumnName("length_in_centimeters");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextSupplyDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_supply_date");

                    b.Property<DateOnly>("PreviousSupplyDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_supply_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("removed_at");

                    b.Property<int?>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("SupplierCity")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_city");

                    b.Property<string>("SupplierName")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL")
                        .HasColumnName("volume");

                    b.Property<float?>("WeightInGrams")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_in_grams");

                    b.Property<float>("WidthInCentimeters")
                        .HasColumnType("REAL")
                        .HasColumnName("width_in_centimeters");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_products_shop_id");

                    b.HasIndex("SupplierName", "SupplierCity")
                        .HasDatabaseName("ix_products_supplier_name_supplier_city");

                    b.ToTable("products", null, t =>
                        {
                            t.HasComment("Represents single product in the Shop.");
                        });
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product_tags");

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<string>("BuildingPhoto")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("building_photo");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("close_time");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_open");

                    b.Property<string>("Logo")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_time");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_date");

                    b.Property<int?>("OwnerContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_contact_id");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_sales");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_shops_address_id");

                    b.HasIndex("OwnerContactId")
                        .HasDatabaseName("ix_shops_owner_contact_id");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.ShopProductsCount", b =>
                {
                    b.Property<int>("ProductsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("products_count");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_products_counts_shop_id");

                    b.ToTable("shop_products_counts", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Supplier", b =>
                {
                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("City")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.HasKey("Name", "City")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lockout_enabled");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShopSupplier", b =>
                {
                    b.Property<int>("ShopsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shops_id");

                    b.Property<string>("SuppliersName")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("suppliers_name");

                    b.Property<string>("SuppliersCity")
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("suppliers_city");

                    b.HasKey("ShopsId", "SuppliersName", "SuppliersCity")
                        .HasName("pk_shop_supplier");

                    b.HasIndex("SuppliersName", "SuppliersCity")
                        .HasDatabaseName("ix_shop_supplier_suppliers_name_suppliers_city");

                    b.ToTable("shop_supplier", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Saritasa.NetForge.Demo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_tag_products_products_id");

                    b.HasOne("Saritasa.NetForge.Demo.Models.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_tag_product_tags_tags_id");
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Product", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("fk_products_shops_shop_id");

                    b.HasOne("Saritasa.NetForge.Demo.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierName", "SupplierCity")
                        .HasConstraintName("fk_products_suppliers_supplier_name_supplier_city");

                    b.Navigation("Shop");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Shop", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_shops_addresses_address_id");

                    b.HasOne("Saritasa.NetForge.Demo.Models.ContactInfo", "OwnerContact")
                        .WithMany()
                        .HasForeignKey("OwnerContactId")
                        .HasConstraintName("fk_shops_contact_infos_owner_contact_id");

                    b.Navigation("Address");

                    b.Navigation("OwnerContact");
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.ShopProductsCount", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_products_counts_shops_shop_id");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Supplier", b =>
                {
                    b.OwnsOne("Saritasa.NetForge.Demo.Models.Director", "Director", b1 =>
                        {
                            b1.Property<string>("SupplierName")
                                .IsUnicode(false)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.Property<string>("SupplierCity")
                                .IsUnicode(false)
                                .HasColumnType("TEXT")
                                .HasColumnName("city");

                            b1.Property<int?>("AddressId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("director_address_id");

                            b1.Property<int>("Age")
                                .HasColumnType("INTEGER")
                                .HasColumnName("director_age");

                            b1.Property<DateOnly>("Birthday")
                                .HasColumnType("TEXT")
                                .HasColumnName("director_birthday");

                            b1.Property<int>("Department")
                                .HasColumnType("INTEGER")
                                .HasColumnName("director_department");

                            b1.Property<string>("Description")
                                .IsUnicode(false)
                                .HasColumnType("TEXT")
                                .HasColumnName("director_description");

                            b1.Property<DateTime>("DirectorSince")
                                .HasColumnType("TEXT")
                                .HasColumnName("director_director_since");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("INTEGER")
                                .HasColumnName("director_is_active");

                            b1.Property<long?>("LastWorkDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("director_last_work_day");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("TEXT")
                                .HasColumnName("director_name");

                            b1.Property<string>("Photo")
                                .IsUnicode(false)
                                .HasColumnType("TEXT")
                                .HasColumnName("director_photo");

                            b1.Property<TimeOnly>("StartWorkTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("director_start_work_time");

                            b1.HasKey("SupplierName", "SupplierCity");

                            b1.HasIndex("AddressId")
                                .IsUnique()
                                .HasDatabaseName("ix_suppliers_director_address_id");

                            b1.ToTable("suppliers");

                            b1.HasOne("Saritasa.NetForge.Demo.Models.Address", "Address")
                                .WithOne()
                                .HasForeignKey("Saritasa.NetForge.Demo.Models.Supplier.Director#Saritasa.NetForge.Demo.Models.Director", "AddressId")
                                .HasConstraintName("fk_suppliers_addresses_director_address_id");

                            b1.WithOwner()
                                .HasForeignKey("SupplierName", "SupplierCity")
                                .HasConstraintName("fk_suppliers_suppliers_name_city");

                            b1.OwnsOne("Saritasa.NetForge.Demo.Models.Company", "Company", b2 =>
                                {
                                    b2.Property<string>("DirectorSupplierName")
                                        .IsUnicode(false)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("name");

                                    b2.Property<string>("DirectorSupplierCity")
                                        .IsUnicode(false)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("city");

                                    b2.Property<int>("EmployeeCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("director_company_employee_count");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(false)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("director_company_name");

                                    b2.HasKey("DirectorSupplierName", "DirectorSupplierCity");

                                    b2.ToTable("suppliers");

                                    b2.WithOwner()
                                        .HasForeignKey("DirectorSupplierName", "DirectorSupplierCity")
                                        .HasConstraintName("fk_suppliers_suppliers_name_city");
                                });

                            b1.Navigation("Address");

                            b1.Navigation("Company")
                                .IsRequired();
                        });

                    b.Navigation("Director");
                });

            modelBuilder.Entity("ShopSupplier", b =>
                {
                    b.HasOne("Saritasa.NetForge.Demo.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_supplier_shops_shops_id");

                    b.HasOne("Saritasa.NetForge.Demo.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersName", "SuppliersCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_supplier_suppliers_suppliers_name_suppliers_city");
                });

            modelBuilder.Entity("Saritasa.NetForge.Demo.Models.Shop", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
