using System.Security.Cryptography;

namespace Saritasa.NetForge.Demo.Infrastructure;

/// <summary>
/// Helpers class for files.
/// </summary>
internal static class FileHelpers
{
    /// <summary>
    /// Securely create a temporary file.
    /// </summary>
    /// <param name="fileExtension">Optional file extension.</param>
    /// <returns>Temporary file.</returns>
    /// <remarks>
    /// See the needs for this method here <see href="https://github.com/saritasa-nest/saritasa-forge-admin/pull/128#discussion_r2020377642"/>.
    /// <br/>
    /// Generate a random file name using the built-in cryptographic RNG.
    /// Generated byte sequences are 512-byte long.
    /// </remarks>
    public static string CreateTemporaryFileSecure(string? fileExtension = null)
    {
        fileExtension ??= string.Empty;
        string fileName;

        // Secure random.
        // Would use /dev/random or /dev/urandom on Linux
        using (var rng = RandomNumberGenerator.Create())
        {
            var bytes = new byte[64];
            rng.GetBytes(bytes);
            fileName = $"{Convert.ToHexString(bytes)}{fileExtension}";
        }

        var tempDirectory = Path.GetTempPath();
        return Path.Join(tempDirectory, fileName);
    }
}